### ISSUE TITLE
Trigger run failed

### ISSUE THREAD

**Issue by qchen0225** [wvuweb/hammer-vm#10]
default: Running: inline script
    default: /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find rails-html-sanitizer-1.0.3 in any of the sources (Bundler::GemNotFound)
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/spec_set.rb:90:in `map!'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/spec_set.rb:90:in `materialize'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/definition.rb:183:in `specs'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/definition.rb:253:in `specs_for'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/definition.rb:235:in `requested_specs'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/runtime.rb:91:in `block in definition_method'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/runtime.rb:20:in `setup'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler.rb:148:in `setup'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/setup.rb:20:in `block in <top (required)>'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/ui/shell.rb:136:in `with_level'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/ui/shell.rb:88:in `silence'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.2.17/lib/bundler/setup.rb:20:in `<top (required)>'
    default: 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    default: 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    default: 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    default: 	from hammer_server.rb:4:in `<main>'
==> default: Trigger run failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by adamjohnson** [comment]
Chen: what versions of Vagrant and VirtualBox do you have installed? You can find out by running `vagrant -v` in your terminal for Vagrant and `virtualbox --version` for VirtualBox.

For what it's worth, I am running v6.0.16 of VirtualBox and v2.2.5 of Vagrant. I can confirm that Hammer-VM works with those versions.

**Comment by qchen0225** [comment]
Hi Adam,
When I type in virtualbox --version, and this is what show up.

DEBUG: issetugid_for_AppKit was called by 0x7fff3b37d05c /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit::_NSCheckForIllegalSetugidApp+0x1d (via 0x7fff3b37cc5a)

I tried to uninstall VirtualBox and then downloaded it again. But it still doesn't solve the problem。

**Comment by adamjohnson** [comment]
If you have VirtualBox installed, you should be able to open the application and go to VirtualBox > About VirtualBox in the top menu bar.

<img width="913" alt="VirtualBox Version window screenshot" src="https://user-images.githubusercontent.com/575865/118162783-27219500-b3ef-11eb-8871-0331f2037632.png">

**Comment by qchen0225** [comment]
I have VirtualBox installed, but
<img width="876" alt="Screen Shot 2021-05-13 at 2 11 46 PM" src="https://user-images.githubusercontent.com/80414161/118167999-5804c880-b3f5-11eb-8305-1b15e53c43f1.png">
<img width="1406" alt="Screen Shot 2021-05-13 at 2 15 27 PM" src="https://user-images.githubusercontent.com/80414161/118168272-aca84380-b3f5-11eb-89e2-6f57f816f33a.png">

**Comment by adamjohnson** [comment]
Thanks for coming back with that.

Have you tried restarting the install process?

If the current process is still trying to run, you can hit `Control + C` to end the current process.

Then, when inside the `~/Sites/hammer-vm` directory, type `vagrant destroy`, Say `Yes` or `Y` to the prompt asking "Are you sure you want to destroy this box".

Once that's done, try typing `vagrant up` again and see what happens.

If this doesn't work, we'll probably have to schedule a time to meet with me and possibly @zeroedin. Let us know!

**Comment by adamjohnson** [comment]
One thing that you might try _before_ doing the steps above is to install [OSX Command Line Tools](https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/): `xcode-select --install`

**Comment by adamjohnson** [comment]
I can confirm that Hammer-VM works on OSX Catalina v10.15.7 using VirtualBox v6.1.22r144080 and Vagrant v2.2.16.

I can also confirm that Hammer-VM works on OSX Mojave 10.14.5 with the same VirtualBox and Vagrant versions.

If you run into issues, try running `vagrant provision` and see if that helps.

**Comment by adamjohnson** [comment]
Sounds like the issue here was the WVU VPN preventing `bundle install` from running on the box. Solution: be sure to **disconnect** from the WVU VPN before running `vagrant up`. 👍
