### ISSUE TITLE
vagrantfile needs a boot_timeout

### ISSUE THREAD

**Issue by architarious** [wvuweb/hammer-vm#3]
Kept getting the following error when running vagrant up:

> Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with the guest machine within the configured ("config.vm.boot_timeout" value) time period.  If you look above, you should be able to see the error(s) that Vagrant had when attempting to connect to the machine. These errors are usually good hints as to what may be wrong.  If you're using a custom box, make sure that networking is properly working and you're able to connect to the machine. It is a common problem that networking isn't setup properly in these boxes. Verify that authentication configurations are also setup properly, as well.  If the box appears to be booting properly, you may want to increase the timeout ("config.vm.boot_timeout") value.

Fixed it by adding the following to my vagrant file:

```
config.vm.boot_timeout = 600
```

Not sure if others have had this problem, just putting it out there.

**Comment by zeroedin** [comment]
@architarious this is an old issue going to close, if you still have this issue with newer versions of hammer let me know I'll add in a configurable option that uses the .env file to increase the boot_timeout.
